(function(){
  const RULES=[
    [/パブリック IP|Public IP/i,"パブリック IP は Azure リソースをインターネットから到達可能にするための IP リソースです。直接公開する場合は NSG などの保護も必要です。"],
    [/プライベート IP/i,"プライベート IP は VNet 内部通信向けで、単独ではインターネットからの到達性を提供しません。"],
    [/Bastion/i,"Azure Bastion は VM にパブリック IP を付けたり RDP/SSH ポートを公開したりせずに管理接続するためのサービスです。"],
    [/Front Door/i,"Azure Front Door はグローバルな HTTP/HTTPS アプリ配信、L7 ルーティング、WAF などのためのサービスで、VM の RDP/SSH 管理用途ではありません。"],
    [/Network Watcher/i,"Azure Network Watcher はネットワークの監視・診断サービスで、接続そのものを提供するサービスではありません。"],
    [/Virtual Desktop/i,"Azure Virtual Desktop は仮想デスクトップ/アプリ配信基盤で、既存 VM への単純な管理接続手段とは役割が異なります。"],
    [/Azure Firewall/i,"Azure Firewall はマネージドなネットワーク ファイアウォールです。トラフィック制御には有効ですが、単に VM へ到達させる手段そのものではありません。"],
    [/S2S|拠点間.*VPN|サイト間.*VPN/i,"Site-to-Site VPN はオンプレミス拠点と Azure VNet を VPN Gateway で接続する方式です。対向機器やゲートウェイ構成が必要です。"],
    [/P2S|ポイント対サイト/i,"Point-to-Site VPN は個々のクライアント端末から Azure VNet へ VPN 接続する方式です。ルート変更時はクライアント構成の更新が必要になる場合があります。"],
    [/NSG|ネットワーク セキュリティ グループ/i,"NSG は NIC またはサブネットの受信/送信トラフィックを 5 タプル条件などで Allow/Deny するステートフル フィルターです。"],
    [/Application Security Group|アプリケーション セキュリティ グループ/i,"Application Security Group (ASG) は NIC をアプリ単位で論理グループ化し、NSG ルールの送信元/宛先として使えます。"],
    [/サービス タグ|Service Tag/i,"Service Tag は Azure サービスの IP 範囲を表す論理名で、個別 VM のグルーピング用途ではありません。"],
    [/ユーザー定義ルート|UDR/i,"UDR は Azure のシステム ルートを上書き/補完し、NVA や Virtual network gateway などへトラフィックを誘導できます。"],
    [/VNet peering|ネットワーク ピアリング|仮想ネットワーク ピアリング/i,"VNet Peering は Azure バックボーン上で VNet 間をプライベート接続します。アドレス空間の重複は許可されません。"],
    [/5 タプル|5-tuple/i,"5 タプル ハッシュは送信元/宛先 IP、送信元/宛先ポート、プロトコルを使って新しいフローをバックエンドへ分散します。"],
    [/ソース IP アフィニティ|Client IP|クライアント IP/i,"Source IP affinity / Client IP は同じクライアントを同じバックエンドへ維持しやすくするセッション永続化設定です。"],
    [/ヘルス プローブ|正常性プローブ/i,"Load Balancer の Health Probe は正常なバックエンドだけへ新規フローを送るための死活監視です。"],
    [/インバウンド NAT/i,"Inbound NAT rule は特定フロントエンド ポートを特定 VM/ポートへ変換する機能で、負荷分散やセッション固定そのものとは別です。"],
    [/netstat/i,"netstat は接続状態や LISTENING ポートを確認する OS コマンドです。"],
    [/Private DNS|プライベート DNS/i,"Azure Private DNS は VNet 内で利用するプライベート DNS ゾーンをマネージド提供します。"],
    [/Public DNS|パブリック DNS/i,"Azure Public DNS はインターネット向けの権威 DNS ホスティングです。プライベート VNet 内専用名前解決とは用途が異なります。"],
    [/DNS Private Resolver/i,"Azure DNS Private Resolver は Azure とオンプレミスなどの DNS 名前解決を転送するマネージド リゾルバーです。Private DNS の自動登録そのものではありません。"],
    [/仮想ネットワーク リンク|virtual network link/i,"Private DNS zone の Virtual network link により VNet からゾーンを解決でき、自動登録も設定できます。"],
    [/\bNS\b.*レコード|NS レコード/i,"NS レコードはゾーン/サブドメインを担当する権威 DNS サーバーを示し、サブドメイン委任に使います。"],
    [/\bCNAME\b/i,"CNAME はあるホスト名を別のホスト名へエイリアスする DNS レコードです。宛先 IP が変わってもホスト名を追従できます。"],
    [/\bSOA\b/i,"SOA は DNS ゾーンの権威情報やシリアル番号などを保持するレコードで、ホスト名エイリアスやサブドメイン委任の主目的には使いません。"],
    [/\bSRV\b/i,"SRV はサービスのホスト名とポートを公開する DNS レコードです。Web App の単純な別名設定には通常使いません。"],
    [/\bTXT\b/i,"TXT は文字列情報を保持し、ドメイン検証や SPF などに使われます。IP 変更へ追従するホスト名エイリアスではありません。"],
    [/テンプレートのエクスポート|Export template/i,"Export template は既存 Azure リソースの構成を ARM テンプレートとして取得する機能です。"],
    [/New-AzResourceGroupDeployment/i,"New-AzResourceGroupDeployment はリソース グループ スコープへ ARM テンプレートをデプロイする PowerShell コマンドレットです。"],
    [/New-AzSubscriptionDeployment/i,"New-AzSubscriptionDeployment はサブスクリプション スコープのテンプレート デプロイに使用します。"],
    [/New-AzManagementGroupDeployment/i,"New-AzManagementGroupDeployment は管理グループ スコープのテンプレート デプロイに使用します。"],
    [/--parameters/i,"--parameters は Azure CLI の ARM/Bicep デプロイでパラメーター値を指定するオプションです。"],
    [/--template-file/i,"--template-file はデプロイするテンプレート ファイルを指定するオプションで、パラメーター値の指定とは役割が異なります。"],
    [/\bcopy\b|copy 要素/i,"ARM template の copy ループは同一種別のリソースやプロパティを複数回生成するために使います。"],
    [/Deployments|デプロイメント/i,"Resource group の Deployments では ARM/Bicep のデプロイ履歴、状態、時刻、操作内容などを確認できます。"],
    [/デタッチ|detach/i,"Managed Disk は対応条件下で VM からデタッチし、別 VM へアタッチできます。データ ディスク移動では元 VM からのデタッチが基本です。"],
    [/Redeploy|再デプロイ/i,"VM Redeploy は OS ディスクや構成を保持したまま VM を別の Azure ホストへ移動するトラブルシューティング操作です。"],
    [/Spot/i,"Azure Spot VM は未使用容量を低価格で利用する代わりに、Azure の容量需要や価格条件によって eviction される可能性があります。"],
    [/Azure Files|ファイル共有/i,"Azure Files は SMB/NFS のマネージド ファイル共有で、複数クライアントからの共有ファイルやコンテナーの永続ボリュームに利用できます。"],
    [/Blob Storage|BLOB/i,"Azure Blob Storage は非構造化オブジェクト データ向けストレージです。SMB ファイル共有とは用途が異なります。"],
    [/Queue Storage|キュー/i,"Azure Queue Storage は大量のメッセージを非同期に保存するキュー サービスで、ファイル システム用途ではありません。"],
    [/Azure SQL Database/i,"Azure SQL Database はリレーショナル データベース サービスです。汎用ファイル共有や Blob 保管とは役割が異なります。"],
    [/イベント駆動|Service Bus/i,"Azure Container Apps は KEDA ベースのイベント駆動スケールで Service Bus などの外部イベントに応じてレプリカ数を変更できます。"],
    [/サイドカー|sidecar/i,"Sidecar はメイン コンテナーと並行して動作し、ログ転送、プロキシ、キャッシュ更新などの補助処理を担当します。"],
    [/初期化 \(?init\)?|init コンテナー/i,"Init container はメイン コンテナー起動前に完了すべき初期化処理向けで、継続的な補助処理には向きません。"],
    [/Application Logging.*Blob|アプリケーション ログ \(BLOB\)/i,"App Service の Application Logging to Blob はアプリケーション ログを Blob Storage に永続保存する方式です。"],
    [/Application Logging.*File|アプリケーション ログ \(ファイル システム\)/i,"App Service の File System logging は一時的なトラブルシューティング向けで、長期永続保存には向きません。"],
    [/Standard/i,"App Service Standard はカスタム ドメイン、より大きなスケール、autoscale など本番向け機能を提供します。"],
    [/Basic/i,"App Service Basic は本番向け基本機能を持ちますが、メトリック ベースの autoscale など一部機能は上位プランが必要です。"],
    [/Free/i,"App Service Free は検証向けで、カスタム ドメインや大規模スケールなど本番要件を満たせない場合があります。"],
    [/Premium/i,"App Service Premium は高性能・高度機能向けですが、要件が Standard で満たせる場合はコスト最小化の観点で過剰になり得ます。"],
    [/App Service/i,"Azure App Service は Web アプリ/API/コンテナーをマネージドでホストし、カスタム ドメインやスケール機能を提供します。"],
    [/AKS|Kubernetes/i,"AKS は Kubernetes の柔軟性を提供しますが、App Service などの PaaS より運用・構成の責任範囲が広くなります。"],
    [/Container Instances/i,"Azure Container Instances は単純なコンテナー実行に適しますが、フル機能の Web ホスティングや高度な autoscale では他サービスが適する場合があります。"],
    [/外部コラボレーション|External collaboration/i,"External collaboration settings は Microsoft Entra B2B のゲスト招待可否や招待権限の範囲を制御します。"],
    [/条件付きアクセス|Conditional Access/i,"Conditional Access はサインイン条件に応じて MFA、ブロック、準拠デバイス要求などを適用するアクセス制御です。ゲスト招待権限そのものの設定ではありません。"],
    [/クロステナント|Cross-tenant/i,"Cross-tenant access settings は別 Entra テナントとの B2B collaboration/direct connect の信頼・受入条件を制御します。"],
    [/アクセス レビュー|Access Review/i,"Access Review はユーザーのアクセス権やグループ メンバーシップを定期的にレビューするための機能です。"],
    [/Guest Inviter|ゲスト招待/i,"Guest Inviter は外部ゲスト招待に特化した Microsoft Entra ロールで、Global Administrator より最小権限です。"],
    [/利用場所|Usage location/i,"Usage location は Microsoft 365 などのライセンス割り当て前に必要となるユーザー属性で、サービス提供地域の判定に使われます。"],
    [/\bReader\b|リーダー/i,"Reader は Azure リソースを閲覧できますが変更できない組み込みロールで、参照のみの要件に適します。"],
    [/\bContributor\b|共同作成者|投稿者/i,"Contributor はリソースの作成・変更・削除が可能ですが、ロール割り当ては管理できません。閲覧のみの要件には過剰です。"],
    [/\bOwner\b|所有者/i,"Owner はリソース管理に加えてアクセス権管理も可能な強いロールです。最小権限が求められる場面では通常過剰です。"],
    [/Tag Contributor|タグ共同作成者/i,"Tag Contributor は Azure リソースのタグ管理に特化した組み込みロールです。"],
    [/Storage Account Contributor|ストレージ アカウント共同作成者/i,"Storage Account Contributor はストレージ アカウントの管理プレーン操作やアクセス キー取得を行えますが、データそのものへのアクセスは別権限です。"],
    [/Blob Data Contributor|BLOB データ共同作成者/i,"Storage Blob Data Contributor は Blob データの読み書き/削除などデータ プレーン権限を持ちますが、ストレージ アカウント キー管理とは別です。"],
    [/Cost Management Contributor|コスト管理共同作成者/i,"Cost Management Contributor はコスト表示、予算、エクスポートなど Cost Management を管理できますが、一般 Azure リソースの変更権限は持ちません。"],
    [/Billing Reader|請求書リーダー/i,"Billing Reader は請求情報の参照向けで、予算など Cost Management 設定を管理する権限とは異なります。"],
    [/削除ロック|CanNotDelete|管理ロック/i,"CanNotDelete ロックは対象リソースや下位リソースの削除を防ぎます。ロック自体を削除できる権限を持つ管理者には解除可能です。"],
    [/共有アクセス署名|SAS/i,"Shared Access Signature (SAS) はストレージ リソースへの権限、対象、開始/有効期限などを限定した一時アクセスを発行できます。"],
    [/アクセス キー/i,"Storage account key はアカウント全体に強いアクセスを与える共有秘密情報で、短時間・最小権限の外部共有には SAS の方が適します。"],
    [/ID ベース|Entra.*認証/i,"ID ベース認証は共有キーではなく Entra ID/AD DS などのユーザー・サービス ID でアクセスを制御します。"],
    [/Data Lake Storage|階層型名前空間/i,"Azure Data Lake Storage Gen2 は Blob Storage に hierarchical namespace を追加し、分析ワークロード向けのディレクトリ/ACL セマンティクスを提供します。"],
    [/\bZRS\b|ゾーン冗長/i,"ZRS は同一リージョン内の複数 Availability Zone に同期複製し、ゾーン障害への耐性を高めます。"],
    [/\bLRS\b|ローカル冗長/i,"LRS は単一リージョン内の単一物理ロケーションで複数コピーを保持します。ゾーン障害全体には対応しません。"],
    [/\bGRS\b|ジオ冗長/i,"GRS はプライマリ リージョンの LRS に加え、別リージョンへ非同期複製します。"],
    [/RA-GRS|読み取りアクセス.*ジオ/i,"RA-GRS は GRS に加えてセカンダリ リージョンからの読み取りアクセスを提供します。"],
    [/バージョン管理|versioning/i,"Blob versioning は Blob 更新時に以前のバージョンを保持します。Object Replication の前提機能でもあります。"],
    [/変更フィード|change feed/i,"Blob change feed は Blob の作成・変更・削除イベントを順序付きログとして保持し、Object Replication のソース側前提です。"],
    [/オブジェクト レプリケーション|Object Replication/i,"Blob Object Replication はブロック Blob を非同期に別ストレージ アカウントへ複製します。source/destination の versioning と source の change feed が必要です。"],
    [/不変|Immutable/i,"Immutable Storage は WORM (Write Once, Read Many) を実現し、保持期間中の変更・削除を防止します。"],
    [/ライフサイクル/i,"Lifecycle Management は Blob の経過日数やアクセス条件に応じて tier 移動や削除を自動化します。WORM 保護とは目的が異なります。"],
    [/アクセス追跡|最終アクセス/i,"Last access time tracking は Blob の最終アクセス時刻を記録し、その時刻を lifecycle rule の条件に利用できます。"],
    [/\bArchive\b/i,"Archive は最安のオフライン層ですが、読み出す前に再水和が必要で、即時アクセス要件には向きません。"],
    [/\bCold\b/i,"Cold は長めの最低保持期間を持つ低頻度アクセス向けオンライン層で、データは即時アクセス可能です。"],
    [/\bCool\b/i,"Cool は低頻度アクセス向けオンライン層で、Hot より保存単価が低く、Archive と異なり即時読み出しできます。"],
    [/\bHot\b/i,"Hot は頻繁にアクセスするデータ向けで、保存単価は高めですがアクセス コストを抑えやすい層です。"],
    [/Packet capture|パケット キャプチャ/i,"Network Watcher Packet Capture は VM/NIC の実パケットを取得し、プロトコル レベルの詳細解析に使います。"],
    [/IP フロー検証|IP flow verify/i,"IP flow verify は指定したフローが NSG により Allow/Deny されるか、および該当ルールを即時確認します。"],
    [/Flow Log|フロー ログ/i,"Flow Logs はネットワーク フローの履歴を記録し、長期分析や Traffic Analytics に利用します。単一通信の即時 NSG 判定には IP flow verify が適します。"],
    [/\bsummarize\b/i,"KQL の summarize は group by と count/sum/avg などの集計を行う演算子です。"],
    [/\bproject\b/i,"KQL の project は出力列の選択・並び替えに使います。集計そのものは行いません。"],
    [/\bextend\b/i,"KQL の extend は計算列を追加する演算子で、グループ集計の主目的には使いません。"],
    [/\bwhere\b/i,"KQL の where は行を条件で絞り込む演算子で、集計は summarize が担当します。"],
    [/Action Group|アクション グループ/i,"Action Group は Azure Monitor/Advisor アラートの通知先や自動アクション (メール、SMS、Webhook、Function、Runbook など) をまとめます。"],
    [/アラート ルール|Alert rule/i,"Alert rule は監視対象、条件、しきい値、重大度など『いつアラートを発火するか』を定義します。"],
    [/Azure Monitor Agent|AMA/i,"Azure Monitor Agent (AMA) は Data Collection Rule と組み合わせて VM/Arc サーバーからログやメトリックを収集します。"],
    [/MARS|Microsoft Azure Recovery Services/i,"MARS agent は Windows Server/クライアントのファイル・フォルダーやシステム状態を Recovery Services vault に直接バックアップします。"],
    [/Recovery Services.*vault|Recovery Services コンテナー/i,"Recovery Services vault は Azure Backup/Site Recovery の保護データやポリシーを管理します。削除前には保護停止や soft-deleted item の処理が必要です。"],
    [/Instant Restore|インスタント回復/i,"Azure VM Backup の Instant Restore はスナップショットを一定期間保持し、復旧ポイントへの高速アクセスを可能にします。"],
    [/SSPR|セルフサービス パスワード/i,"SSPR はユーザー自身によるパスワード リセット機能です。オンプレミス AD への password writeback には適切な Entra ID ライセンスと同期構成が必要です。"],
    [/\bP1\b/i,"Microsoft Entra ID P1 は Conditional Access、グループベース ライセンス、オンプレミスへの password writeback を含む SSPR などの機能要件で使われます。"],
    [/\bP2\b/i,"Microsoft Entra ID P2 は P1 に加えて Identity Protection や PIM など高度な ID ガバナンス/リスク機能を提供します。"],
    [/Free/i,"Free エディションは基本 ID 機能を提供しますが、高度な SSPR/Conditional Access など一部機能は上位ライセンスが必要です。"]
  ];

  const TIPS=[
    [/Bastion/i,"「RDP/SSH をインターネットに公開しない」「VM に Public IP を持たせない」なら Bastion を最優先で連想します。"],
    [/最小限の特権|Reader|Guest Inviter|Tag Contributor|Cost Management Contributor/i,"AZ-104 では『最小限の特権』が出たら、要件を満たす最も狭い組み込みロールを選びます。"],
    [/ZRS|可用性ゾーン/i,"「同一リージョン」「複数 Availability Zone」なら ZRS。別リージョンまで含める場合は GRS/GZRS 系を検討します。"],
    [/Object Replication|オブジェクト レプリケーション|versioning|変更フィード/i,"Object Replication は『source/destination の versioning + source の change feed』をセットで覚えます。"],
    [/Archive|Cool|Cold|Hot/i,"アクセス層は『アクセス頻度』『即時取得が必要か』『最低保持期間』の3点で切り分けます。"],
    [/NSG|IP flow/i,"NSG 問題では「どこに関連付くか (NIC/Subnet)」「どのルールが効くか」「即時判定なら IP flow verify」を分けて考えます。"],
    [/Load Balancer|ヘルス プローブ|5 タプル|セッション永続/i,"Load Balancer は『Health Probe=正常性』『Distribution mode=振り分け方』『Session persistence=固定性』を別概念として整理します。"],
    [/ARM|テンプレート|copy|New-AzResourceGroupDeployment/i,"ARM/Bicep はスコープを見抜くことが重要です。Resource Group / Subscription / Management Group でデプロイ コマンドが変わります。"],
    [/App Service|autoscale|Standard|Basic/i,"App Service は『プランの機能差』が頻出です。autoscale、deployment slots、custom domain、instance 上限を要件ごとに確認します。"],
    [/Private DNS|DNS/i,"DNS は『Public/Private』『ゾーンの委任』『VNet link』『Resolver』を役割ごとに分けて覚えます。"],
    [/SAS|アクセス キー/i,"Storage の一時共有では『期限・権限を絞れる SAS』、アカウント全体に強い権限を与える key は避ける、が基本です。"],
    [/不変|Immutable/i,"「一定期間変更・削除不可」= Immutable/WORM。「古いデータを移動/削除」= Lifecycle Management と切り分けます。"],
    [/MARS|Backup|Recovery Services|Instant Restore/i,"Backup は『何を守るか (VM全体/ファイル)』『どこへ保存するか』『復元速度』でサービス/エージェントを切り分けます。"],
    [/SSPR|Guest|外部コラボレーション/i,"Entra 問題では『ユーザー種類』『同期有無』『ライセンス』『ロール』を先に整理すると誤答を減らせます。"],
    [/UDR|ルート/i,"NVA 経由の強制ルーティングは UDR と next hop=Virtual appliance が基本形です。"]
  ];

  const EXTRA_RULES=[
    [/^80$/,"TCP 80 は HTTP の既定ポートです。HTTPS や SMB、RDP の要件には一致しません。"],
    [/^25$/,"TCP 25 は SMTP のサーバー間メール配送で使われる代表的なポートです。"],
    [/^587$/,"TCP 587 は SMTP Submission で使われる代表的なポートです。"],
    [/^443$/,"TCP 443 は HTTPS の既定ポートです。Web の暗号化通信には適しますが、SMB や RDP のポートではありません。"],
    [/^3389$/,"TCP 3389 は RDP の既定ポートです。Windows VM のリモート デスクトップ管理に使います。"],
    [/^22$/,"TCP 22 は SSH の既定ポートです。Linux/SSH 管理に使います。"],
    [/^53$/,"53 番ポートは DNS で使用されます。SSH/HTTPS/RDP などのアプリケーション ポートとは異なります。"],
    [/^445$/,"TCP 445 は SMB の既定ポートで、Azure Files を SMB で直接利用するときに必要です。"],
    [/^5671$/,"TCP 5671 は TLS を使用する AMQP で使われる代表的なポートです。Azure Files の SMB 接続には使いません。"],
    [/Get-AzVirtualNetworkUsageList/i,"Get-AzVirtualNetworkUsageList は仮想ネットワークの使用量情報を取得する Azure PowerShell コマンドで、OS 内の待受ポート確認には使いません。"],
    [/nbtstat/i,"nbtstat は NetBIOS over TCP/IP の名前テーブルや統計情報を確認するコマンドで、TCP 80 の LISTENING 状態を直接一覧する用途ではありません。"],
    [/Test-NetConnection/i,"Test-NetConnection は指定先への疎通やポート接続テストに使えますが、サーバー上の全待受ポートを一覧する設問では netstat が直接的です。"],
    [/ipconfig \/flushdns/i,"ipconfig /flushdns は Windows の DNS リゾルバー キャッシュを消去します。待受ポート確認には使いません。"],
    [/nslookup/i,"nslookup は DNS 名前解決を問い合わせるツールで、待受ポート確認には使いません。"],
    [/route print/i,"route print は Windows の IP ルーティング テーブルを表示します。待受ソケットの確認には使いません。"],
    [/Azure 仮想マシン上の DNS サーバー/i,"VM 上に独自 DNS サーバーを構築すれば名前解決は可能ですが、OS の構築・パッチ・可用性管理が必要になり、『管理作業を最小限』という要件では Private DNS より不利です。"],
    [/Azure 提供の名前解決/i,"Azure 提供の既定名前解決は同一 VNet 内などの基本用途には使えますが、複数 VNet で共通の独自 DNS サフィックスを管理する用途には Private DNS zone が適します。"],
    [/hosts ファイル/i,"hosts ファイルでも個別の名前解決はできますが、各 VM への手動配布・更新が必要でスケールせず、管理作業を最小化できません。"],
    [/\bA\b( レコード)?$/i,"DNS A レコードはホスト名を IPv4 アドレスへ直接対応付けます。IP 変更に自動追従するホスト名エイリアスには CNAME が適します。"],
    [/\bPTR\b/i,"PTR は逆引き DNS で IP アドレスから名前を解決するためのレコードです。Web App の別名設定には使いません。"],
    [/\bMX\b/i,"MX はメール配送先サーバーを指定する DNS レコードです。Web アプリのホスト名エイリアスには使いません。"],
    [/NAT Gateway/i,"NAT Gateway はサブネットからインターネットへの送信接続を提供するサービスで、Private DNS の自動登録や VNet 間接続の機能ではありません。"],
    [/上位 SKU/i,"SKU のアップグレードは機能や上限を変える操作ですが、分散アルゴリズムやヘルス プローブの誤構成を直接解消する操作ではありません。"],
    [/タイムアウトの設定を増やす/i,"Idle timeout の変更が有効なケースはありますが、バックエンドの正常性や NSG/待受ポートを確認せず最初に変更する項目ではありません。"],
    [/セッション永続化の設定を変更する/i,"Session persistence は同一クライアントを同じバックエンドへ送りやすくする設定です。一般的な接続障害の基本切り分けでは probe・待受・NSG を先に確認します。"],
    [/VM を再起動/i,"VM 再起動は症状を一時的に変える可能性はありますが、原因特定にならず、構成要件を満たす直接的な操作ではありません。"],
    [/Get-AzVM と New-AzVM/i,"Get-AzVM/New-AzVM は VM 情報取得や VM 作成のコマンドで、既存 VM 構成を ARM テンプレートとしてエクスポートする方法ではありません。"],
    [/Save-AzDeploymentScriptLog/i,"Save-AzDeploymentScriptLog は Deployment Script のログ取得に関するコマンドで、既存リソースの ARM テンプレート化には使いません。"],
    [/New-AzVM/i,"New-AzVM は VM を直接作成するコマンドレットです。既存 ARM テンプレートをリソース グループ スコープへデプロイするコマンドではありません。"],
    [/配列値を含むようにテンプレートを変更/i,"パラメーターとして渡すべき値をテンプレートへハードコードすると再利用性が下がります。インライン入力の要件には --parameters を使います。"],
    [/個別のパラメーター ファイル/i,"パラメーター ファイルは有効な方法ですが、『インライン パラメーターとして渡す』という設問条件には一致しません。"],
    [/API のバージョン/i,"apiVersion は ARM リソース プロバイダー API のバージョン指定であり、同一リソースを複数作る繰り返し回数の指定ではありません。"],
    [/Azure サブスクリプション ID/i,"subscription ID はデプロイ先などを識別しますが、テンプレート内で同じリソースを複数生成する仕組みではありません。"],
    [/リソース グループの場所/i,"resource group の location はデプロイ メタデータの場所に関係しますが、複数 VM の反復生成には関係しません。"],
    [/dependsOn/i,"dependsOn はリソース間のデプロイ順序/依存関係を表します。複数インスタンスの反復生成には copy を使います。"],
    [/outputs/i,"outputs はデプロイ後に返す値を定義します。リソースを反復作成する機能ではありません。"],
    [/variables/i,"variables はテンプレート内部で再利用する値を定義します。反復そのものは copy が担当します。"],
    [/condition/i,"condition はリソースをデプロイするかどうかの条件分岐です。指定回数の反復生成には copy を使います。"],
    [/VM1 を停止|VM2 を停止|VM-A を停止/i,"データ ディスクのホット デタッチに対応する構成なら VM を停止する必要はなく、停止は『できるだけ早く』という要件に対して余分です。"],
    [/VM1 を再起動/i,"再起動してもデータ ディスクは VM に接続されたままです。ディスク移動の最初の操作にはなりません。"],
    [/スナップショットを必ず作成/i,"スナップショットは安全策として有用な場合がありますが、ディスクを別 VM へ移すための必須手順ではありません。"],
    [/CPU 使用率/i,"CPU メトリックは CPU ベースのスケーリングには使えますが、Service Bus メッセージ数をトリガーにする要件ではイベント駆動スケールが必要です。"],
    [/HTTP トラフィック|HTTP スケーリング/i,"HTTP スケーリングは受信 HTTP 要求量に応じる方式で、Service Bus のメッセージ数を基準にする要件とは異なります。"],
    [/メモリ使用量/i,"メモリ メトリックを使ったスケールは可能なケースがありますが、Service Bus メッセージ数という外部イベント条件には一致しません。"],
    [/手動スケーリング/i,"手動スケーリングではキューの増減に自動追従できません。"],
    [/特権/i,"特権コンテナーは高い OS 権限が必要な用途で、キャッシュ更新やログ転送などの補助プロセス パターンとは異なります。"],
    [/ジョブ/i,"Container Apps Job は完了するバッチ/イベント駆動タスクに適します。メイン アプリと常時並行動作する補助処理は sidecar が適します。"],
    [/新しい Web アプリを作成/i,"既存 Web App を別リソース グループへ移動する要件なので、同等の新規 Web App を作り直す必要はありません。"],
    [/詳細なエラー メッセージ/i,"Detailed error messages は HTTP エラーの詳細ページを記録する診断機能で、アプリケーション コードが出力するログを重大度で永続保存する設定とは別です。"],
    [/^詳細$|Verbose/i,"Verbose/詳細は Warning より低いレベルまで大量に記録するため、『Warning 以上だけ』というフィルター要件には一致しません。"],
    [/デプロイ スロット/i,"Deployment slot はステージングやスワップに使う機能で、CPU/メモリ メトリックに基づくスケール条件を作る機能ではありません。"],
    [/インスタンス数に基づいてスケーリング/i,"固定インスタンス数の設定は自動的な CPU しきい値スケールではありません。メトリックベースの autoscale rule が必要です。"],
    [/^A$/,"A レコードはホスト名を固定 IPv4 アドレスへ向けます。App Service の IP 変更に追従する要件では CNAME が適します。"],
    [/ユーザー アカウントが無効/i,"UPN の #EXT# はアカウント無効を示す記号ではなく、B2B 外部ユーザーの表現に使われます。"],
    [/管理ロールが割り当て/i,"#EXT# から管理ロール割り当ての有無は判断できません。"],
    [/ユーザーが削除/i,"#EXT# は削除状態を表しません。B2B 外部ユーザーの UPN 形式です。"],
    [/^(名|姓|その他のメール アドレス|ユーザーの種類)$/,"これらはユーザー属性ですが、Microsoft 365 ライセンス割り当て前に地域判定のため必須となる Usage location ではありません。"],
    [/スナップショットを作成して削除/i,"snapshot/delete は NotActions で除外されているため、スナップショットを削除できません。"],
    [/仮想マシンを作成/i,"Microsoft.Compute/*/read は読み取り権限であり、VM 作成に必要な write 権限を与えません。"],
    [/新しいコスト分析/i,"Cost analysis は可視化・分析であり、予算しきい値に達したときの自動アクションを構成するものではありません。"],
    [/管理グループ/i,"Azure 管理ロックは管理グループには直接適用できません。サブスクリプション、リソース グループ、個々の ARM リソースが対象です。"],
    [/ストレージ アカウント データ/i,"管理ロックは ARM 管理プレーンのリソースに適用され、Blob などストレージ内部のデータ オブジェクトを直接ロックする機能ではありません。"],
    [/Microsoft\.Compute.*write.*カスタム ロール/i,"VM の write 権限はタグ以外の VM 構成変更も許し得るため、タグだけを管理させる最小権限としては広すぎます。"],
    [/各仮想マシンのアクセス制御|仮想マシンのアクセス制御/i,"各 VM に個別割り当てすると管理作業が増えます。全 VM が対象なら適切な最小ロールをサブスクリプション スコープで 1 回割り当てる方が要件に合います。"],
    [/サブスクリプションのポリシー設定/i,"Azure Policy は準拠性の評価・強制に使いますが、特定ユーザーへタグ操作権限を付与する RBAC の代替ではありません。"],
    [/CDN/i,"CDN はコンテンツ配信を高速化・キャッシュするサービスで、ストレージへの期限付き認可を発行する機能ではありません。"],
    [/パブリック ネットワーク アクセス|Public access/i,"Public network access はネットワーク到達性に関する設定で、ユーザー ID による SMB 認証を構成するものではありません。"],
    [/ポイントインタイム リストア/i,"Point-in-time restore は Blob データを過去時点へ復旧する機能で、Object Replication の必須前提ではありません。"],
    [/カスタム Azure ロール/i,"RBAC ロールは操作権限を制御しますが、一定期間の WORM 保持を保証する仕組みではありません。"],
    [/変更履歴フィード/i,"Change feed は変更イベントを記録する機能で、Blob の変更・削除そのものを禁止しません。"],
    [/ログ アラート/i,"Log alert はログ クエリ条件に基づいて通知を発生させる機能で、実パケットを取得して通信内容を検査する機能ではありません。"],
    [/ネットワーク入力とネットワーク出力/i,"Network In/Out メトリックは転送量の監視に使えますが、個々のパケット内容を検査することはできません。"],
    [/診断ログ/i,"診断ログは履歴分析に有用ですが、特定 5 タプルがどの NSG ルールで Allow/Deny されるかを即時判定する用途では IP flow verify が直接的です。"],
    [/60 日より前/i,"Alert の User response は経過日数だけで自動的に Closed へ変わる状態ではありません。"],
    [/条件が存在しなくなった/i,"基礎条件が解消すると Monitor condition は Resolved になりますが、User response の Closed は別のユーザー管理状態です。"],
    [/毎週のバックアップ ポイントの保持期間/i,"週次 recovery point の長期保持期間を短くしても、Instant Restore snapshot の保持日数を 2 日へ変更する前提条件は解決しません。"],
    [/^コンテナー$/,"Blob コンテナーは Blob オブジェクトの格納単位です。この設問が求める SMB の ID ベース認証対象は Azure Files のファイル共有です。"],
    [/^テーブル$/,"Table Storage は NoSQL キー/属性データ向けで、SMB ファイル共有の ID 認証対象ではありません。"],
    [/オブジェクトのレプリケーション/i,"Object Replication は Blob を別アカウントへ複製する可用性/配置機能で、アクセス層を選んで保存コストを最小化する機能ではありません。"],
    [/ストレージ アカウント キーをローテーション/i,"キー ローテーションは資格情報のセキュリティ運用で、最終アクセス時刻を使う lifecycle rule の前提ではありません。"],
    [/^通知$/,"通知は結果として行う動作の種類であり、独立した Azure Monitor リソースとして条件やアクションを定義するものではありません。"],
    [/セキュリティで保護された Webhook/i,"Secure Webhook は Action Group 内で選べるアクションの 1 種類です。アラート条件/重大度を定義する Alert rule の代替ではありません。"],
    [/VMAccess/i,"VMAccess Extension はユーザー/SSH/RDP アクセスの回復などに使う拡張機能で、Log Analytics へ JSON ログを継続収集するエージェントではありません。"],
    [/Custom Script|カスタム スクリプト/i,"Custom Script Extension は VM 内でスクリプトを実行する仕組みで、継続的な Azure Monitor ログ収集エージェントではありません。"],
    [/DSC/i,"DSC Extension は Desired State Configuration の適用向けで、カスタム JSON ログ収集のための監視エージェントではありません。"],
    [/VM1 と VM2 を削除/i,"Recovery Services vault を削除するために保護対象 VM 本体を削除する必要はありません。バックアップ保護と vault の依存関係を解除します。"],
    [/読み取りロック/i,"ReadOnly/管理ロックを追加すると削除をさらに妨げます。vault 削除準備の操作ではありません。"],
    [/Microsoft Azure Backup Server|MABS/i,"MABS は複数ワークロードを保護するバックアップ サーバー製品で、1 台の Windows Server のファイル/フォルダーを vault へ直接送る最小構成では MARS が適します。"],
    [/Site Recovery プロバイダー|Mobility Service/i,"Site Recovery は災害復旧レプリケーション向けで、ファイル/フォルダーの Azure Backup エージェントではありません。"],
    [/Azure 接続マシン|Connected Machine/i,"Azure Connected Machine Agent は Azure Arc でサーバーを Azure 管理へ接続するためのエージェントで、MARS バックアップを実行しません。"],
    [/バックアップ ポリシーを作成/i,"MARS はサーバー側でスケジュールを構成しますが、まず vault credentials を使って Server1 を vault に登録する必要があります。"],
    [/ソフト削除を有効/i,"Soft delete は保護機能ですが、MARS サーバーを vault へ登録してバックアップ可能にする次の必須手順ではありません。"],
    [/セキュリティ設定を変更/i,"一般的なセキュリティ設定変更では MARS エージェントと vault の登録関係は作られません。"],
    [/Entra ID 無料|Entra ID Free/i,"ハイブリッド SSPR でオンプレミスへの password writeback を必要とする要件では Free では不足し、P1 以上が必要です。"],
    [/グローバル管理者|Global Administrator/i,"Global Administrator でも操作できますが権限が非常に広く、ゲスト招待だけという最小権限要件では過剰です。"],
    [/グループ管理者|Groups Administrator/i,"Groups Administrator はグループ管理向けで、外部ゲスト招待だけを許可する最小ロールではありません。"],
    [/セキュリティ管理者|Security Administrator/i,"Security Administrator はセキュリティ設定管理向けで、ゲスト招待専用の最小ロールではありません。"],
    [/Add-AzRoleDefinition/i,"Add-AzRoleDefinition はカスタム ロール定義を追加する操作で、既存ロールを -Name で取得する式の修正にはなりません。"],
    [/Get-AzRoleAssignment/i,"Get-AzRoleAssignment はロール割り当てを取得するコマンドで、RoleDefinition の名前解決とは異なります。"],
    [/Set-AzRoleAssignment/i,"この設問では既存 RoleDefinition を正しい名前で取得する必要があり、ロール割り当ての設定コマンドへ置き換える問題ではありません。"],
    [/管理単位/i,"Administrative Unit は Microsoft Entra オブジェクトの管理スコープ委任に使います。Azure VM の部門分類メタデータにはタグが適します。"],
    [/ストレージ アカウント$/i,"Storage account はデータ格納リソースであり、VM を部門別に分類するためのメタデータ機能ではありません。"],
    [/Automation アカウント/i,"Automation account は Runbook などの自動化をホストしますが、Advisor アラートの複数通知先を直接まとめる役割は Action Group です。"],
    [/容量予約グループ/i,"Capacity Reservation Group は VM コンピュート容量を予約するためのリソースで、アラート通知とは無関係です。"],
    [/New-AzureRmResourceGroup/i,"New-AzureRmResourceGroup はリソース グループ作成用の旧 AzureRM コマンドです。既存リソースの削除保護には使いません。"],
    [/Set-AzResourceGroup/i,"Set-AzResourceGroup はリソース グループの属性更新に使いますが、削除保護そのものは management lock で実現します。"],
    [/RG1 にタグ|タグを追加/i,"タグは分類用メタデータであり、削除をブロックする保護機構ではありません。"],
    [/診断設定/i,"Diagnostic settings はログ/メトリックの送信先を構成します。ARM デプロイ履歴の作成日時を確認する場所ではありません。"],
    [/^Policy$|Azure Policy/i,"Azure Policy は構成準拠性の評価/強制に使います。ARM template のデプロイ履歴を表示するブレードではありません。"],
    [/Azure ポリシーを適用/i,"Azure Policy はコンプライアンス制御であり、VM を別の物理ホストへ移動する操作ではありません。"],
    [/Azure タグを適用/i,"タグは分類メタデータであり、VM の実行ホストを変更しません。"],
    [/別の Azure サブスクリプションに移動/i,"サブスクリプション移動は管理スコープの変更で、物理ホスト障害を避けるためのホスト再配置ではありません。"],
    [/一日のうちの時間|時刻/i,"Spot VM の eviction は時刻そのものでは決まりません。Azure の容量需要や価格条件が主な要因です。"],
    [/料金プラン/i,"Pricing plan は性能/機能を決めますが、既存コンテナー イメージを使うかコードを公開するかは Publish 設定で指定します。"],
    [/ランタイム スタック/i,"Runtime stack はコード実行環境の選択であり、カスタム Docker イメージを公開するモードの指定とは異なります。"],
    [/VM Scale Sets|仮想マシン スケールセット/i,"VM Scale Sets でもスケール可能ですが、OS/VM 運用責任が増えるため、PaaS で管理作業を最小化する Web アプリ要件では App Service が適します。"],
    [/仮想ネットワーク ゲートウェイ/i,"Virtual Network Gateway は VPN/ExpressRoute 接続に使います。NVA 経由へ任意のトラフィックを誘導するのは UDR の役割です。"],
    [/既定のルートを変更|システム ルートを変更/i,"Azure のシステム ルート自体を直接編集するのではなく、User Defined Route で上書き/補完します。"],
    [/Private Endpoint|プライベート エンドポイント/i,"Private Endpoint は PaaS サービスを VNet 内のプライベート IP で公開する機能で、P2S クライアントに新しい VNet ルートを配る操作ではありません。"],
    [/New-SelfSignedCertificate/i,"証明書ベース P2S では証明書作成が必要な場合がありますが、ピアリング追加後の新ルート反映には VPN client profile の再取得が必要です。"],
    [/^仮想ネットワーク$/i,"NSG は VNet 全体へ直接関連付けるのではなく、サブネットまたは NIC に関連付けます。"],
    [/^仮想マシン$|VM リソース本体/i,"NSG は VM リソースそのものではなく、VM の NIC または所属サブネットへ関連付けます。"],
    [/仮想マシンのサブネット/i,"サブネット全体を宛先にすると対象外の VM も含まれます。特定 VM 群だけなら ASG で論理グループ化します。"],
    [/Add-AzLoadBalancerFrontendIpConfig/i,"これは Load Balancer のフロントエンド IP 構成を追加するコマンドで、NSG/セキュリティ ルール作成には使いません。"],
    [/Add-AzNetworkInterfaceTapConfig/i,"Network Interface TAP の構成用で、NSG の作成やルール定義には使いません。"],
    [/セッション永続化を \[なし\]/i,"None は既定の 5-tuple 分散で、クライアントを同じバックエンドへ固定する要件には合いません。"],
    [/すべてに DNS サーバーを構成/i,"各 VNet で DNS サーバー IP を指定していても、VNet 間の IP 到達性がなければ VM1 へ問い合わせできません。接続性を作る必要があります。"],
    [/ルート テーブルを作成/i,"UDR だけでは別 VNet 間の基盤接続は作られません。まず VNet peering などで到達性を確立します。"],
    [/2 個目の NIC/i,"NIC を追加してもインターネットから到達する Public IP は自動的に得られません。"],
    [/Azure DNS$/i,"Azure DNS は名前解決サービスで、VM への RDP/SSH 管理接続や待受ポート確認を提供しません。"],
    [/Azure Load Balancer$/i,"Load Balancer は L4 トラフィック分散サービスで、VM へ安全に管理接続する Bastion の代替ではありません。"],
    [/VM のサイズを上げる/i,"VM サイズ変更は性能/容量を増やしますが、Health Probe の失敗やポート待受不備の原因診断にはなりません。"],
    [/接続モニター|Connection monitor/i,"Connection Monitor は継続的なエンドツーエンド接続監視向けです。単一フローの NSG Allow/Deny と該当ルールを即時返すのは IP flow verify です。"],
    [/トポロジ|Topology/i,"Network Watcher Topology はネットワーク リソースの関係を可視化しますが、特定フローの NSG 判定やパケット内容を取得しません。"],
    [/VPN トラブルシューティング/i,"VPN troubleshoot は VPN Gateway/connection の診断向けで、VM 間の NSG 判定とは異なります。"],
    [/アクセス制御 \(IAM\)/i,"IAM は RBAC のロール割り当てを管理します。既存リソース構成の ARM テンプレートを取得する機能ではありません。"],
    [/--subscription/i,"--subscription は操作対象サブスクリプションを指定するための引数で、テンプレート パラメーター値を渡すものではありません。"],
    [/--confirm-with-what-if/i,"--confirm-with-what-if は変更内容のプレビュー/確認に関係するオプションで、パラメーター値指定ではありません。"],
    [/Azure Table Storage/i,"Table Storage は NoSQL データ ストアで、ACI のファイルシステム型永続ボリュームには Azure Files が適します。"],
    [/アクセス パッケージ/i,"Access Package は Entitlement Management でリソース アクセスを申請・期限管理する機能です。B2B ゲスト招待権限の全体設定とは別です。"],
    [/\bPIM\b/i,"PIM は特権ロールの JIT/期限付きアクティブ化を管理します。ゲスト招待を誰に許可するかの基本設定ではありません。"],
    [/サービス プリンシパル/i,"Service principal はアプリ/サービスの ID であり、#EXT# を含む B2B ユーザー UPN の種類ではありません。"],
    [/マネージド ID/i,"Managed Identity は Azure リソースに付与するサービス ID で、B2B ゲスト ユーザーではありません。"],
    [/デバイス オブジェクト/i,"Device object は Entra に登録/参加した端末を表し、#EXT# UPN のユーザーとは異なります。"],
    [/^(部署|携帯電話番号|役職)$/,"これらはプロファイル属性ですが、ライセンス割り当てで地域要件を判断する Usage location の代わりにはなりません。"],
    [/ディスクを削除/i,"NotActions で disk/snapshot の delete が除外されている場合、削除操作は許可されません。"],
    [/VM を削除/i,"read 権限やディスク write 権限から VM delete 権限は得られません。"],
    [/User Access Administrator/i,"User Access Administrator はロール割り当て管理に強い権限を持ちます。単なる閲覧要件には Reader が最小です。"],
    [/可用性セット|Availability Set/i,"Availability Set は障害ドメイン/更新ドメインへ VM を分散する可用性機能で、分類やアラート通知先の管理には使いません。"],
    [/ストレージ アカウント キーを共有/i,"Account key はアカウント全体に強い権限を与えるため、期限付き・最小権限の外部共有には SAS が適します。"],
    [/Static website/i,"Static website は Blob Storage から静的 Web コンテンツを配信する機能で、versioning や ID 認証の代替ではありません。"],
    [/NFS v3|NFS 3\.0/i,"NFS はファイル アクセス プロトコルの設定で、Blob Object Replication の前提となる versioning ではありません。"],
    [/Access tracking/i,"Access tracking は最終アクセス時刻の追跡で、Object Replication の前提ではありません。"],
    [/Soft delete/i,"Soft delete は削除されたデータを一定期間復元可能にする機能です。WORM 不変性や Object Replication の必須 versioning とは役割が異なります。"],
    [/Traffic Analytics/i,"Traffic Analytics は flow log を集約分析してトラフィック傾向を可視化します。特定の NSG 判定を即時調べる用途には IP flow verify が適します。"],
    [/Dependency Agent/i,"Dependency Agent は VM Insights の依存関係可視化などに使われます。カスタム JSON ログを Log Analytics へ取り込む主体は Azure Monitor Agent です。"],
    [/保護対象の VM 本体を削除/i,"vault の削除に必要なのは Backup の保護停止と依存関係の解除であり、保護対象 VM 自体の削除ではありません。"],
    [/Soft delete を無効/i,"Secure by Default が有効な現行環境では soft delete を無効化できない場合があります。Instant Restore の保持期間変更とは無関係です。"],
    [/VM Extension を追加/i,"MARS の vault 登録には vault credentials を使います。一般的な VM Extension 追加はその代替ではありません。"],
    [/ストレージ アカウント キーを作成/i,"MARS は Recovery Services vault の資格情報で登録し、Storage account key は使用しません。"],
    [/Authentication methods/i,"Authentication methods は MFA/パスワードレス等の認証方式を構成します。ゲスト招待権限の範囲設定ではありません。"],
    [/Identity Protection/i,"Identity Protection はサインイン/ユーザー リスク検出とリスクポリシー向けで、ゲスト招待権限管理とは異なります。"],
    [/ロール定義 ID の GUID/i,"Get-AzRoleDefinition -Name に渡すのはロール名です。GUID を使う場合は ID に対応した取得方法を使います。"],
    [/サブスクリプション ID|リソース グループ ID/i,"これらは Azure スコープ識別子で、Get-AzRoleDefinition -Name が期待するロール名ではありません。"],
    [/Resource lock/i,"Resource lock は削除/変更保護向けで、分類・可視化・ダッシュボード表示の用途ではありません。"],
    [/Availability zone/i,"Availability Zone は物理的に分離されたデータセンター ゾーンで、リソース分類メタデータではありません。"],
    [/すべてのリソースへ個別タグ/i,"タグは削除を防止しません。削除保護には CanNotDelete lock を使います。"],
    [/Policy の Audit/i,"Audit ポリシーは非準拠を記録しますが、削除操作そのものをブロックする管理ロックではありません。"],
    [/Set-AzVM/i,"Set-AzVM は VM 構成更新に使うコマンドで、ARM テンプレートの RG スコープ デプロイではありません。"],
    [/^Locks$/,"Locks ブレードは管理ロックを表示/設定します。ARM deployment の実行日時を確認する場所ではありません。"],
    [/^Tags$/,"Tags は分類メタデータです。デプロイ履歴の日時は Deployments で確認します。"],
    [/Access control \(IAM\)/i,"IAM は RBAC を管理する画面で、ARM デプロイ履歴の確認には使いません。"],
    [/--resource-group/i,"--resource-group はデプロイ対象のリソース グループを指定します。配列などのテンプレート パラメーター値は --parameters で渡します。"],
    [/--mode/i,"--mode は complete/incremental などデプロイ モードに関係し、パラメーター値の指定ではありません。"],
    [/Resize/i,"Resize は VM サイズを変更します。物理ホストを切り替えるトラブルシューティング操作は Redeploy です。"],
    [/Reimage/i,"Reimage は OS イメージを再適用する破壊的な操作になり得ます。ホストだけを変更したい要件には Redeploy が適します。"],
    [/Capture/i,"Capture は VM からイメージを作成する操作で、実行ホストを変更する機能ではありません。"],
    [/ディスク使用率/i,"Spot eviction はゲスト OS のディスク使用率を直接条件にはしません。容量需要や価格条件が主因です。"],
    [/Runtime stack/i,"Runtime stack はコードの実行環境を選ぶ設定です。カスタムコンテナーの利用では Publish/Container を選びます。"],
    [/Authentication を無効/i,"認証設定はアプリへのアクセス制御で、コンテナー イメージを使う Publish モードの指定ではありません。"],
    [/Service Endpoint/i,"Service Endpoint は PaaS サービスへの VNet 経路/サービス側 ACL に関する機能で、NVA へ全トラフィックを強制ルーティングしません。"],
    [/Private Endpoint を作成/i,"Private Endpoint は PaaS の private IP 化で、P2S クライアントのルート更新には関係しません。"],
    [/Route Table/i,"Route Table は経路制御に使いますが、特定 VM 群を NSG の宛先として論理グループ化する用途では ASG が適します。"],
    [/Outbound rule/i,"Outbound rule は Load Balancer の送信 SNAT を制御する機能で、受信セッションの固定方法ではありません。"],
    [/HA Ports/i,"HA Ports は全ポート/プロトコルを対象に内部負荷分散するシナリオ向けで、クライアント セッション固定の設定ではありません。"],
    [/Traffic Manager/i,"Traffic Manager は DNS ベースのグローバル トラフィック分散で、VNet 間のプライベート IP 到達性を作りません。"],
    [/A レコードを追加|A レコードを編集/i,"A レコードはホスト名を IPv4 アドレスへ直接対応付けますが、子ドメインを別 DNS サーバーへ委任するには親ゾーンの NS レコードが必要です。"],
    [/カスタム DNS サーバーを使用するように構成/i,"カスタム DNS サーバー指定は名前解決先を変更する設定ですが、Azure Private DNS ゾーンへの VM レコード自動登録は Virtual Network Link の auto-registration で構成します。"],
    [/Microsoft\.Compute.*書き込みアクセス許可.*カスタム ロール/i,"VM write 権限を含むカスタム ロールはタグ以外の変更も許し得ます。タグ付けだけなら Tag Contributor の方が最小権限です。"],
    [/^初期化$/i,"Init コンテナーはメイン コンテナー起動前に一度だけ実行する初期化処理向けです。継続的なキャッシュ更新には sidecar が適します。"],
    [/VNet ピアリング$/i,"VNet Peering は VNet 間のプライベート接続を作りますが、インターネット上の外部ベンダーから VM へ直接到達させる手段ではありません。"],
    [/^ポリシー$/i,"Azure Policy はリソースの準拠性評価・強制に使います。既存構成を ARM テンプレートとして取得する機能ではありません。"],
    [/VM-A を削除/i,"ディスクを別 VM へ移すために元 VM 自体を削除する必要はありません。データ ディスクをデタッチします。"],
    [/CPU のみによるスケーリング/i,"CPU ベースのスケールは CPU 使用率に反応します。Service Bus のメッセージ数に追従するにはイベント駆動スケールが必要です。"],
    [/ローカル一時ファイルのみ/i,"App Service のローカル ファイルシステム ログは一時的な診断向けで、再起動を越える長期永続保存には Blob が適します。"],
    [/ブラウザー キャッシュ/i,"ブラウザー キャッシュはクライアント側の Web コンテンツ キャッシュで、サーバーのアプリケーション ログ保存先にはなりません。"],
    [/Always On を無効/i,"Always On はアイドル時のアプリ停止を防ぐ機能です。無効化しても CPU/メモリに基づく autoscale は有効になりません。"],
    [/^NS$/i,"NS レコードは DNS ゾーンの権威サーバーを示します。Web App のサブドメインを既定ホスト名へエイリアスする用途では CNAME を使います。"],
    [/Azure DNS ゾーン/i,"DNS ゾーンは名前解決用のリソースで、Cost Management の予算しきい値から VM を自動停止する仕組みには使いません。"],
    [/Management Group/i,"Management Group は複数サブスクリプションを階層管理するスコープです。ダッシュボード表示、Advisor 通知、タグ分類などの直接的な機能ではありません。"],
    [/^parse$/i,"KQL の parse は文字列から構造化フィールドを抽出する演算子です。件数などをグループ集計するには summarize を使います。"],
    [/Activity log のみ/i,"Activity Log は Azure 管理プレーン イベントの履歴です。複数種のアラート インスタンスの User response や状態を一覧管理する画面そのものではありません。"],
    [/Resource Graph のみ/i,"Resource Graph でもアラートをクエリできますが、ポータルで発生アラートの状態・履歴を直接管理する標準 UI は Alert instances です。"],
    [/^Advisor$/i,"Azure Advisor はコスト・信頼性・セキュリティ等の推奨事項を提供します。発生済み Azure Monitor alert instance の状態管理画面ではありません。"],
    [/Azure Site Recovery のみ/i,"Azure Site Recovery は VM/サーバーの災害復旧レプリケーション向けです。定期バックアップと復元ポイント保持は Azure Backup の役割です。"],
    [/Storage account の CORS|^CORS$/i,"CORS はブラウザーのクロス オリジン要求を制御する設定で、バックアップの Instant Restore 保持や Blob の不変性には関係しません。"],
    [/DNS TTL/i,"DNS TTL は名前解決結果のキャッシュ時間です。Azure Backup のスナップショット保持期間とは無関係です。"],
    [/Lifecycle rule/i,"Lifecycle rule は Blob の tier 移動や削除を自動化します。WORM として変更・削除を禁止する要件には Immutable policy が必要です。"],
    [/^VM を停止する$/i,"VM を停止しても Instant Restore snapshot の保持設定は変わりません。バックアップ ポリシーの頻度/保持を変更します。"],
    [/Azure Event Grid/i,"Event Grid はイベント配信サービスで、ACI にマウントする永続共有ファイル システムではありません。"],
    [/Deployment slot を作|Deployment slot を増/i,"Deployment slot はステージング/スワップ用です。カスタム コンテナーの公開方式やメトリック autoscale を有効にする操作ではありません。"],
    [/^init$/i,"Init container はメイン コンテナー起動前の一度きりの初期化処理向けです。継続してプロキシ等を担うなら sidecar を使います。"],
    [/New-AzVirtualNetworkGateway/i,"New-AzVirtualNetworkGateway は VPN/ExpressRoute 用の仮想ネットワーク ゲートウェイを作成するコマンドで、NSG の作成には使いません。"],
    [/New-AzLoadBalancer/i,"New-AzLoadBalancer は Azure Load Balancer を作成するコマンドで、NSG とセキュリティ ルールの作成には使いません。"],
    [/VM 名を変更/i,"VM 名を変更しても Load Balancer の probe や session persistence の問題は解決しません。"],
    [/Resource Group を移動/i,"Resource Group の移動は管理上の配置変更で、Load Balancer の接続一貫性や正常性プローブを修正する操作ではありません。"]
  ];

  const QOPTION={
    "s1-q27":{0:"Group1 には対象メンバーが 3 人いるため 0 ライセンスではありません。",1:"Group1 のメンバーは User1、User2、User3 の 3 人なので 1 ライセンスでは不足します。",3:"User4 は所有者ですが Group1 のメンバーではないため、グループベース ライセンスの対象に含めません。"},
    "s1-q46":{1:"Microsoft Practice Assessment の想定では最大 14 日なので 30 日は選びません。なお、この 14 日制限は現行 Learn では明確な現行制限として確認しにくいため監査注記を参照してください。",2:"Practice 想定値 14 日と一致しません。",3:"Practice 想定値 14 日と一致しません。"},
    "s1-q49":{0:"既定 Azure VM バックアップ ポリシーの日次復旧ポイント保持は 30 日であり、7 日ではありません。",1:"既定保持は 30 日であり、14 日ではありません。",3:"既定保持は 30 日であり、90 日ではありません。"},
    "s2-q19":{0:"User1 も同期メンバーであり password writeback が有効なので SSPR 対象です。User2 だけではありません。",2:"User3 は B2B ゲストで、contoso.com の SSPR ポリシーでメンバーと同じようには扱いません。User1 も対象なのでこの組合せは誤りです。",3:"B2B ゲスト User3 を含める点が誤りです。Practice 想定では User1 と User2 が対象です。"},
    "s2-q46":{1:"VM2 は NIC2 の NSG3 で port 80 が Deny されるため到達できません。",2:"VM3 は NIC3 の NSG3 で port 80 が Deny されるため到達できません。",3:"VM4 は Subnet2 に関連付いた NSG3 で port 80 が Deny されるため到達できません。"},
    "sim-q027":{0:"GroupA のライセンス対象はメンバー 4 人なので 1 人ではありません。",2:"所有者がメンバーでないなら 5 人目は対象外です。ライセンス対象は 4 人です。",3:"グループベース ライセンスは所有者だけではなくグループのメンバーへ適用されます。"},
    "sim-q069":{1:"クラウド メンバー UserA も SSPR 対象なので UserC のみではありません。",2:"同期メンバー UserB も password writeback により対象です。一方 UserC は B2B ゲストです。",3:"B2B ゲスト UserC をリソース テナントの SSPR 対象として含める点が誤りです。"},
    "sim-q096":{1:"Subnet と NIC の両方に NSG がある場合、受信通信は両方で許可される必要があります。NSG-B が Deny なので接続できません。",2:"Public IP SKU はこの設問の NSG Allow/Deny 結果を覆しません。",3:"VM サイズは NSG の通信許可判定に影響しません。"}
  };

  function noteFor(opt,q,index){
    if(q&&QOPTION[q.uid]&&QOPTION[q.uid][index]) return QOPTION[q.uid][index];
    for(const [re,n] of EXTRA_RULES){ if(re.test(String(opt))) return n; }
    for(const [re,n] of RULES){ if(re.test(String(opt))) return n; }
    return "";
  }
  function decision(q){
    const t=q.q||"";
    const points=[];
    const pairs=[
      [/最小限の特権/,"最小権限"],
      [/管理作業を最小限/,"運用負荷を最小化"],
      [/コストを最小限/,"コスト最小化"],
      [/インターネットに公開せず|公開したくありません/,"インターネット非公開"],
      [/自動|自動的/,"自動化"],
      [/永続/,"永続性"],
      [/高可用性/,"高可用性"],
      [/可用性ゾーン/,"可用性ゾーン"],
      [/数秒以内|即時/,"即時アクセス"],
      [/長期|年間|年保存|バックアップ/,"長期保管/バックアップ"],
      [/外部ユーザー|ゲスト/,"外部 ID"],
      [/複数選択|2 つ|2つ|3 つ|3つ/,"複数条件を同時に満たす"],
      [/RDP|SSH/,"管理接続"],
      [/SMB/,"SMB"],
      [/NSG/,"NSG 判定"],
      [/ロード バランサー|Load Balancer/i,"負荷分散"],
      [/ARM|テンプレート/i,"ARM/Bicep デプロイ"]
    ];
    for(const [re,label] of pairs){if(re.test(t)&&!points.includes(label))points.push(label);}
    if(!points.length) return "設問の最後にある『何を実現したいか』を先に特定し、その要件を直接満たす Azure 機能を選びます。";
    return "この問題の決め手は「"+points.slice(0,3).join("」「")+"」です。要件を満たす機能だけを残して選択肢を消去します。";
  }
  function tip(q){
    const blob=(q.q+" "+q.o.join(" ")+" "+q.a.map(i=>q.o[i]).join(" "));
    for(const [re,t] of TIPS){if(re.test(blob))return t;}
    return "サービス名の暗記だけでなく、『対象』『スコープ』『必要な前提条件』『管理負荷/コスト』をセットで覚えると、類似問題にも対応できます。";
  }
  function build(q){
    const correct=new Set(q.a||[]);
    const options=(q.o||[]).map((opt,i)=>{
      const n=noteFor(opt,q,i);
      if(correct.has(i)){
        return {index:i,ok:true,text:n||"この選択肢が設問の要件を直接満たします。"};
      }
      return {index:i,ok:false,text:n ? n+" ただし、この設問で要求されている条件を直接満たす選択肢ではありません。" : "この選択肢では設問の主要要件を直接満たせません。正解選択肢の役割・スコープ・前提条件と比較して消去します。"};
    });
    return {
      decision:decision(q),
      correctReason:(q.e||"")+" "+(q.a||[]).map(i=>noteFor(q.o[i])).filter(Boolean).join(" "),
      options,
      tip:tip(q)
    };
  }
  window.AZ104_EXPLAIN={build};
})();